/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team6.client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.UnknownHostException;

import edu.duke.ece651.team6.shared.GameBasicSetting;
<<<<<<< HEAD
import edu.duke.ece651.team6.shared.MyName;
=======
>>>>>>> 7c17bd0bb94143c251fa4e93c0dc235bc33f4882

public class App {
  Client client;

  TextPlayer player;

  /**
   * Construct an app with 2 params
   * 
   * @param client for handling interactions (e.g. connection and communication)
   *               with server
   * @param player for handling interaction (e.g. user input for commands,
   *               initializations, play turns) with players
   */
  public App(Client client, TextPlayer player) {
    this.client = client;
    this.player = player;
<<<<<<< HEAD
  }
  // Takes an Inputstream and transfer its bytes into a string, then return the
  // string
  // private String getStringFromIS(InputStream is) throws IOException {
  // byte[] bytes = new byte[0];
  // bytes = new byte[is.available()];
  // is.read(bytes);
  // return new String(bytes);
  // }

  public String getMessage() {
    return "Hello from the client for " + MyName.getName();
=======
>>>>>>> 7c17bd0bb94143c251fa4e93c0dc235bc33f4882
  }

  public static void main(String[] args) throws IOException, UnknownHostException, ClassNotFoundException {
    /* 1. Build connection */
    Client client = null;
    GameBasicSetting setting = null;
    BufferedReader input = null;

    if (args.length != 2) {
      System.out
          .println("Invalid Argument! Usage: ./client/build/install/client/bin/client <server_addr> <server_port>");
      System.out.println("For example, \"./client/build/install/client/bin/client localhost 12345c\"");
      System.out.println("or \"./client/build/install/client/bin/client vcm-30819.vm.duke.edu 8999\"");
      System.exit(1);
    }

    try {
      // create a client obejct and connect it to the server
      client = new Client(args[0], Integer.valueOf(args[1]));
      System.out.println((String) client.recvObject());
      setting = client.recvGameBasicSetting();
      input = new BufferedReader(new InputStreamReader(System.in));
    } catch (UnknownHostException e) {
      System.out.println("UnknownHostException " + e.getMessage());
    } catch (IOException e) {
      System.out.println(e.getMessage());
    }

    TextPlayer player = new TextPlayer(client, input, System.out, setting);
<<<<<<< HEAD
    player.displayGameSetting("game setting");
=======
    player.displayGameSetting();
>>>>>>> 7c17bd0bb94143c251fa4e93c0dc235bc33f4882

    // App app = new App(client, player);

    /* 2. Initiation Phase */
    player.placeUnit();

    /* 3. Play Phase */
    player.playGame();

    /* 4. Close Phase */
    try {
      input.close();
      client.closeSocket();
    } catch (IOException e) {
      System.out.println(e.getMessage());
    }
  }
}
