/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team6.server;

import java.io.IOException;

public class App {
  public static void main(String[] args) throws NumberFormatException, IOException, ClassNotFoundException {
    if (args.length != 1) {
      throw new IllegalArgumentException(
          "Invalid Argument! Usage: ./server/build/install/server/bin/server <server_port>");
    }
    GameReactor gr = new GameReactor(Integer.parseInt(args[0]), 10);
    gr.run();
    gr.close();
  }
}
