/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team6.server;
import edu.duke.ece651.team6.shared.MyName;
import java.io.IOException;

public class App {
  public String getMessage() {
    return "Hello from the server for "+ MyName.getName();
  }
  public static void main(String[] args) throws IOException, ClassNotFoundException {
    RiscMaster riscMaster = new RiscMaster(12345, 2);
    riscMaster.init();
    riscMaster.prepare();
    while (true) {
      if (riscMaster.playOneTurn()) {
        break;
      }
    }
    riscMaster.finish();
  }
}
